---
- hosts: all
  gather_facts: False
- name: install basics
  hosts: all
  become: True
  gather_facts: False
  roles:
    - { role: 'basics', tags: 'basics' }

- name: prepare all
  hosts: all
  become: True
  gather_facts: True
  roles:
    - { role: 'prepare', tags: 'prepare' }

- name: init master
  hosts: masters
  become: True
  gather_facts: False
  roles:
    - { role: 'master', tags: 'master' }
#    - { role: 'nfs-server', tags: 'nfs-server' }

- name: setup nodes
  hosts: all
  become: True
  gather_facts: False
  vars:
    master_hostname: "{{ groups['masters'][0] }}"
  roles:
    - { role: 'nodes', tags: 'nodes' }
#    - { role: 'nfs-client', tags: 'nfs-client' }
